/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as WorkspaceIdRouteImport } from './routes/workspace/$id'
import { Route as OauthProviderCallbackRouteImport } from './routes/oauth/$provider/callback'
import { Route as WorkspaceIdIndexRouteImport } from './routes/workspace/$id/index'
import { Route as WorkspaceIdMRouteImport } from './routes/workspace/$id/m'
import { Route as WorkspaceIdSLListidRouteImport } from './routes/workspace/$id/s/l/$listid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthProviderCallbackRoute = OauthProviderCallbackRouteImport.update({
  id: '/oauth/$provider/callback',
  path: '/oauth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdMRoute = WorkspaceIdMRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdSLListidRoute = WorkspaceIdSLListidRouteImport.update({
  id: '/s/l/$listid',
  path: '/s/l/$listid',
  getParentRoute: () => WorkspaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$id': typeof WorkspaceIdRouteWithChildren
  '/oauth/$provider/callback': typeof OauthProviderCallbackRoute
  '/workspace/$id/m': typeof WorkspaceIdMRoute
  '/workspace/$id/': typeof WorkspaceIdIndexRoute
  '/workspace/$id/s/l/$listid': typeof WorkspaceIdSLListidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/$provider/callback': typeof OauthProviderCallbackRoute
  '/workspace/$id/m': typeof WorkspaceIdMRoute
  '/workspace/$id': typeof WorkspaceIdIndexRoute
  '/workspace/$id/s/l/$listid': typeof WorkspaceIdSLListidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$id': typeof WorkspaceIdRouteWithChildren
  '/oauth/$provider/callback': typeof OauthProviderCallbackRoute
  '/workspace/$id/m': typeof WorkspaceIdMRoute
  '/workspace/$id/': typeof WorkspaceIdIndexRoute
  '/workspace/$id/s/l/$listid': typeof WorkspaceIdSLListidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$id'
    | '/oauth/$provider/callback'
    | '/workspace/$id/m'
    | '/workspace/$id/'
    | '/workspace/$id/s/l/$listid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/$provider/callback'
    | '/workspace/$id/m'
    | '/workspace/$id'
    | '/workspace/$id/s/l/$listid'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$id'
    | '/oauth/$provider/callback'
    | '/workspace/$id/m'
    | '/workspace/$id/'
    | '/workspace/$id/s/l/$listid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  WorkspaceIdRoute: typeof WorkspaceIdRouteWithChildren
  OauthProviderCallbackRoute: typeof OauthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/$provider/callback': {
      id: '/oauth/$provider/callback'
      path: '/oauth/$provider/callback'
      fullPath: '/oauth/$provider/callback'
      preLoaderRoute: typeof OauthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id/': {
      id: '/workspace/$id/'
      path: '/'
      fullPath: '/workspace/$id/'
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/workspace/$id/m': {
      id: '/workspace/$id/m'
      path: '/m'
      fullPath: '/workspace/$id/m'
      preLoaderRoute: typeof WorkspaceIdMRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/workspace/$id/s/l/$listid': {
      id: '/workspace/$id/s/l/$listid'
      path: '/s/l/$listid'
      fullPath: '/workspace/$id/s/l/$listid'
      preLoaderRoute: typeof WorkspaceIdSLListidRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
  }
}

interface WorkspaceIdRouteChildren {
  WorkspaceIdMRoute: typeof WorkspaceIdMRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
  WorkspaceIdSLListidRoute: typeof WorkspaceIdSLListidRoute
}

const WorkspaceIdRouteChildren: WorkspaceIdRouteChildren = {
  WorkspaceIdMRoute: WorkspaceIdMRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
  WorkspaceIdSLListidRoute: WorkspaceIdSLListidRoute,
}

const WorkspaceIdRouteWithChildren = WorkspaceIdRoute._addFileChildren(
  WorkspaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  WorkspaceIdRoute: WorkspaceIdRouteWithChildren,
  OauthProviderCallbackRoute: OauthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
